name: Android Release Workflow

on:
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 18
          distribution: 'temurin'

      - name: Set Google Maps API Key in local.properties
        env:
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
        run: echo "GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}" >> local.properties

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Generate Debug APK
        run: ./gradlew clean assembleDebug

      - name: Create release and upload apk
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v1.0.5-alpha
          asset_path: app/build/outputs/apk/debug/app-debug.apk
          asset_name: debug.apk
          asset_content_type: application/zip

      - name: Release build
        run: ./gradlew assembleRelease
